### ISSUE TITLE
Missing "what next?"

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/laser-tripwire#2]
The worksheet is missing a final "what next?" step. It's currently showing the final step header with the "what next" icon.

**Comment by lauraclay** [comment]
Where are you seeing the 'what next?' icon? I can't see it on the live site.

The worksheet was always missing a 'what next?' step. If this is required of all resources, let me know so I can flag it when editing- that way incomplete resources won't go live.

**Comment by bennuttall** [comment]
This is where I'm seeing it:

![screenshot from 2016-03-18 11-18-24](https://cloud.githubusercontent.com/assets/1609725/13876334/3a4f5aa6-ecfb-11e5-84dd-56555a259f91.png)

It's required of all worksheets in all resources, so that the step numbers are included.
