### ISSUE TITLE
Links for tweet and photo don't work, they return users to step 1 in the project

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/laser-tripwire#23]
https://projects.raspberrypi.org/en/projects/laser-tripwire/5

I've emailed user to say we'll let hi know once fixed. Please assign back to me on resolution so I can email him before we close.

**Comment by libxx1** [comment]
Hey @MarcScott  can you take a look at this please. It's the 'tweet' and 'picture' links. I'm not sure where the links are meant to point to as I can't find repositories for them or any mention in learning. Cheers, Liz

**Comment by MarcScott** [comment]
Links updated
