### ISSUE TITLE
Capacitor orientation in breadboard diagrams

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/laser-tripwire#4]
Ideally, the capacitor should be flipped horizontally so the grey stripe is on the ground side.   People sometimes look at pictures and forget to read the text.  Also, after time, someone may have "conveniently" cut both the capacitor legs the same length.

**Comment by samalderhyde** [comment]
Thanks Steve, I'll make that change to the diagram now

**Comment by bennuttall** [comment]
@samalderhyde did you do this?

**Comment by samalderhyde** [comment]
I have now
